name: PR Test Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '.github/**'
      - 'styleguide/**'
      - '.editorconfig'

jobs:
  pr-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Save Gradle cache
        uses: actions/cache@v2
        with:
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --no-daemon

